import { chromium } from 'playwright'
const b = await chromium.launch({ args: ['--use-gl=angle', '--use-angle=swiftshader', '--enable-unsafe-swiftshader'] })
const p = await b.newPage({ viewport: { width: 1720, height: 950 } })
p.setDefaultTimeout(90000)
p.on('dialog', (d) => d.accept())
p.on('pageerror', (e) => console.log('PAGE ERROR:', e.message))
await p.goto('http://127.0.0.1:3000')
await p.evaluate(() => localStorage.setItem('bbq_view', '3d'))
await p.fill('input[type=password]', 'Ember&Oak-2417')
await p.click('button[type=submit]')
await p.waitForSelector('.topbar')
await p.click('text=✨ Assistant').catch(() => {})
await p.click('.topbar >> text=Presets')
await p.waitForTimeout(400)
await p.click('text=Island Entertainer')
await p.waitForTimeout(1500)
await p.keyboard.press('f')
await p.waitForTimeout(600)
// select a back-run frame via store (grill frame f idx 0)
await p.evaluate(() => {
  const s = window.__bbq()
  s.select({ kind: 'frame', id: s.design.frames[0].id })
})
// orbit so the island occludes the back run: drag down to lower the camera
const c = await p.locator('.stage3d canvas').boundingBox()
await p.mouse.move(c.x + c.width / 2, c.y + c.height / 2)
await p.mouse.down()
await p.mouse.move(c.x + c.width / 2, c.y + c.height / 2 - 170, { steps: 10 })
await p.mouse.up()
await p.waitForTimeout(700)
await p.screenshot({ path: 'screenshots/3d-xray.png', clip: { x: 280, y: 54, width: 1150, height: 800 } })
console.log('done')
await b.close()
