import { chromium } from 'playwright'
const b = await chromium.launch({ args: ['--use-gl=angle', '--use-angle=swiftshader', '--enable-unsafe-swiftshader'] })
const p = await b.newPage({ viewport: { width: 1720, height: 950 } })
p.setDefaultTimeout(90000)
p.on('dialog', (d) => d.accept())
p.on('pageerror', (e) => console.log('PAGE ERROR:', e.message))
p.on('console', (m) => m.type() === 'error' && console.log('CONSOLE:', m.text().slice(0, 300)))
await p.goto('http://127.0.0.1:3000')
await p.evaluate(() => localStorage.setItem('bbq_view', '3d'))
await p.fill('input[type=password]', process.env.BBQ_USER_PASSWORD)
await p.click('button[type=submit]')
await p.waitForSelector('.topbar')
await p.click('text=✨ Assistant').catch(() => {})
await p.click('.topbar >> text=Presets')
await p.waitForTimeout(400)
await p.click('text=U-Shape Bar')
await p.waitForTimeout(1500)
await p.keyboard.press('f')
await p.waitForTimeout(800)
await p.screenshot({ path: 'screenshots/3d-u.png', clip: { x: 280, y: 54, width: 1150, height: 800 } })
// orbit: drag right-button? OrbitControls left-drag rotates
const c = await p.locator('.stage3d canvas').boundingBox()
await p.mouse.move(c.x + c.width / 2, c.y + c.height / 2)
await p.mouse.down()
await p.mouse.move(c.x + c.width / 2 + 260, c.y + c.height / 2 - 60, { steps: 12 })
await p.mouse.up()
await p.waitForTimeout(600)
await p.screenshot({ path: 'screenshots/3d-orbit.png', clip: { x: 280, y: 54, width: 1150, height: 800 } })
console.log('done')
await b.close()
