import { chromium } from 'playwright'
const b = await chromium.launch({ args: ['--use-gl=angle', '--use-angle=swiftshader', '--enable-unsafe-swiftshader'] })
const p = await b.newPage({ viewport: { width: 1720, height: 950 } })
p.setDefaultTimeout(60000)
p.on('dialog', (d) => d.accept())
await p.goto('http://127.0.0.1:3000')
await p.evaluate(() => localStorage.setItem('bbq_view', '3d'))
await p.fill('input[type=password]', 'Ember&Oak-2417')
await p.click('button[type=submit]')
await p.waitForSelector('.topbar')
await p.evaluate(() => {
  const s = window.__bbq()
  s.setLayout('u')
  const f1 = s.addFrame(90); s.placeAppliance(f1, 'grill-90')
  s.addFrame(60, undefined, false, 'left')
  s.addFrame(60, undefined, false, 'right')
})
await p.waitForTimeout(800)
await p.keyboard.press('f')
await p.waitForTimeout(400)
// orbit to near top-down: drag up a lot
const c = await p.locator('.stage3d canvas').boundingBox()
await p.mouse.move(c.x + c.width/2, c.y + c.height/2)
await p.mouse.down()
await p.mouse.move(c.x + c.width/2, c.y + c.height/2 + 260, { steps: 15 })
await p.mouse.up()
await p.waitForTimeout(500)
await p.screenshot({ path: 'screenshots/corner-top.png', clip: { x: 300, y: 54, width: 1120, height: 780 } })
await b.close()
