import { launch3d, signupFresh, enterBuilder } from './_helper.mjs'
const { browser, page: p } = await launch3d()
await signupFresh(p)
await enterBuilder(p)
await p.evaluate(() => {
  const s = window.__bbq()
  s.setLayout('u')
  const f1 = s.addFrame(90); s.placeAppliance(f1, 'grill-90')
  s.addFrame(60, undefined, false, 'left')
  s.addFrame(60, undefined, false, 'right')
})
await p.waitForTimeout(1000)
await p.keyboard.press('f')
await p.waitForTimeout(500)
await p.screenshot({ path: 'screenshots/corner-front.png', clip: { x: 300, y: 54, width: 1120, height: 780 } })
// orbit to top-down
const c = await p.locator('.stage3d canvas').boundingBox()
await p.mouse.move(c.x + c.width / 2, c.y + c.height / 2)
await p.mouse.down()
await p.mouse.move(c.x + c.width / 2, c.y + c.height / 2 + 260, { steps: 15 })
await p.mouse.up()
await p.waitForTimeout(500)
await p.screenshot({ path: 'screenshots/corner-top.png', clip: { x: 300, y: 54, width: 1120, height: 780 } })
await browser.close()
console.log('done')
