import { launch3d, signupFresh } from './_helper.mjs'
const { browser, page: p } = await launch3d()
let fail=0; const check=(n,c)=>{console.log(`${c?'PASS':'FAIL'}  ${n}`); if(!c)fail++}
try {
  await signupFresh(p)
  await p.click('.home-new'); await p.waitForSelector('.wiz'); await p.click('.wiz-head .btn-ghost'); await p.waitForSelector('.topbar')
  await p.evaluate(()=>{
    const s=window.__bbq()
    const a=s.addFrame(90); s.placeAppliance(a,'grill-90')
    const b=s.addFrame(60); s.placeAppliance(b,'sink-40')
    s.createGroup('Grill run', window.__bbq().design.frames.map(f=>f.id))
  })
  await p.click('.panel button:has-text("DIY")')
  await p.waitForSelector('.diy-page')
  await p.click('button:has-text("Skip questions")')
  await p.waitForSelector('.diy-plan-head', {timeout:240000})
  check('plan generated', true)
  const text = await p.$eval('.admin-content', e=>e.textContent)
  check('plan is imperial', /(inch|"|ft\b|feet|')/i.test(text))
  // expandable step card with tools + substeps
  await p.click('.diy-step-head')
  await p.waitForSelector('.diy-step-body', {timeout:4000})
  check('step expands with substeps', (await p.$$('.diy-substeps li')).length>=2)
  check('step has its own tool chips', (await p.$$('.diy-tool-chip')).length>=1)
  // generate IKEA diagram (image model)
  await p.click('.diy-step-diagram button')
  await p.waitForSelector('.diy-step-diagram img', {timeout:120000})
  check('IKEA-style diagram generated', await p.$('.diy-step-diagram img')!==null)
  await p.screenshot({ path:'screenshots/diy-step.png' })
  // ask a question about the step
  await p.fill('.diy-ask input', 'Can I use screws instead of welding here?')
  await p.click('.diy-ask button')
  await p.waitForSelector('.diy-qa', {timeout:60000})
  check('step Q&A answered', (await p.$eval('.diy-qa p', e=>e.textContent)).length>30)
  // shopping list: click row → copy + store links
  await p.click('.diy-checklist li .diy-check-main')
  await p.waitForSelector('.diy-shop-links', {timeout:4000})
  const links = await p.$$eval('.diy-shop-links a', els=>els.map(a=>a.href))
  check('Home Depot / Lowes / Google links', links.some(l=>l.includes('homedepot.com')) && links.some(l=>l.includes('lowes.com')))
  // persistence: reload → plan still there (the reported bug)
  await p.reload(); await p.waitForSelector('.topbar', {timeout:20000})
  await p.click('.topbar button:has-text("DIY")')
  await p.waitForSelector('.diy-page')
  await p.click('.admin-nav button')
  await p.waitForSelector('.diy-plan-head', {timeout:8000})
  check('plan SURVIVES reload (bug fixed)', await p.$('.diy-plan-head')!==null)
  await p.screenshot({ path:'screenshots/diy-shop.png' })
} catch(e){ console.log('ERR', e.message); fail++ }
await browser.close()
console.log(fail?`\n${fail} FAIL`:'\nALL PASS'); process.exit(fail?1:0)
