import { chromium } from 'playwright'
const b = await chromium.launch({ args: ['--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader'] })
const p = await b.newPage({ viewport: { width: 1720, height: 950 } })
p.setDefaultTimeout(60000); p.on('dialog', d=>d.accept()); p.on('pageerror', e=>console.log('PAGE ERROR:', e.message))
await p.goto('http://127.0.0.1:3000')
await p.evaluate(()=>{localStorage.clear(); localStorage.setItem('bbq_view','3d')})
await p.reload()
await p.fill('input[type=password]',process.env.BBQ_USER_PASSWORD); await p.click('button[type=submit]'); await p.waitForSelector('.topbar')
const unit = await p.evaluate(()=>window.__bbq().unit)
console.log('default unit:', unit)
// open Base & layout, check width shows feet, type feet value
await p.click('text=Structure').catch(()=>{})
await p.click('.collapsible-head'); await p.waitForTimeout(200)
const inputs = await p.$$('.collapsible-body .size-input')
const shown = await inputs[0].inputValue()
console.log('width input shows:', JSON.stringify(shown))
await inputs[0].click({clickCount:3}); await inputs[0].fill("14'6"); await inputs[0].press('Enter'); await p.waitForTimeout(300)
const w = await p.evaluate(()=>window.__bbq().design.ground.width)
console.log("typed 14'6 -> width cm:", w, '(expect ~442)')
await b.close()
