import { chromium } from 'playwright'
const b = await chromium.launch()
const p = await b.newPage({ viewport: { width: 1720, height: 950 } })
p.setDefaultTimeout(90000)
p.on('dialog', (d) => d.accept())
await p.goto('http://127.0.0.1:3000')
await p.fill('input[type=password]', process.env.BBQ_USER_PASSWORD)
await p.click('button[type=submit]')
await p.waitForSelector('.topbar')
await p.click('text=✨ Assistant').catch(() => {})
await p.click('.topbar >> text=Presets')
await p.waitForTimeout(400)
await p.click('text=Island Entertainer')
await p.waitForTimeout(700)
await p.keyboard.press('f')
await p.waitForTimeout(600)
await p.screenshot({ path: 'screenshots/island-canvas.png', clip: { x: 280, y: 54, width: 1150, height: 800 } })
await b.close()
console.log('ok')
