import { chromium } from 'playwright'
const b = await chromium.launch()
const p = await b.newPage({ viewport: { width: 1720, height: 950 }, deviceScaleFactor: 1 })
p.setDefaultTimeout(90000)
p.on('dialog', (d) => d.accept())
await p.goto('http://127.0.0.1:3000')
await p.fill('input[type=password]', 'Ember&Oak-2417')
await p.click('button[type=submit]')
await p.waitForSelector('.topbar')
await p.click('text=✨ Assistant').catch(() => {})
await p.click('.topbar >> text=Presets')
await p.waitForTimeout(400)
await p.click('text=Island Entertainer')
await p.waitForTimeout(700)
// zoom in on the kitchen: press + a few times after fit
await p.keyboard.press('f')
await p.waitForTimeout(300)
for (let i = 0; i < 3; i++) await p.keyboard.press('+')
await p.waitForTimeout(500)
await p.screenshot({ path: 'screenshots/island-zoom.png', clip: { x: 500, y: 100, width: 900, height: 700 } })
await b.close()
console.log('ok')
