import { launch3d } from './_helper.mjs'
const { browser, page: p } = await launch3d()
await p.goto('http://127.0.0.1:3000')
await p.evaluate(()=>{localStorage.clear(); localStorage.setItem('bbq_view','3d')})
await p.reload()
await p.waitForSelector('.landing'); await p.click('.landing-cta'); await p.waitForSelector('.topbar')
await p.evaluate(()=>{ const s=window.__bbq(); const a=s.addFrame(90); s.placeAppliance(a,'grill-90'); s.addFrame(60); s.setPergola(true) })
await p.waitForTimeout(700); await p.keyboard.press('f'); await p.waitForTimeout(500)
await p.screenshot({ path:'screenshots/pergola.png', clip:{x:200,y:60,width:1300,height:720} })
console.log('pergola set:', await p.evaluate(()=>window.__bbq().design.pergola))
await browser.close()
