import { chromium } from 'playwright'
const b = await chromium.launch()
const p = await b.newPage({ viewport: { width: 1600, height: 950 } })
p.setDefaultTimeout(30000); p.on('pageerror', e=>console.log('PAGE ERROR:', e.message))
await p.goto('https://bbq-build.onrender.com')
await p.evaluate(()=>localStorage.clear()); await p.reload()
await p.waitForSelector('.landing', { timeout: 20000 })
console.log('landing loads:', Boolean(await p.$('.landing')))
await p.click('.landing-cta')
await p.waitForSelector('.topbar', { timeout: 15000 })
console.log('guest builder loads:', Boolean(await p.$('.topbar')))
console.log('guest banner:', Boolean(await p.$('.guest-banner')))
await p.screenshot({ path: '/home/sagi/workspace/SagiWorkspace/bbqBuild/screenshots/prod-landing.png' })
await b.close()
